apiVersion: v1
kind: ConfigMap
metadata:
  name: osd-serviceorchestration
  namespace: pagerduty-operator
  labels:
    api.openshift.com/managed: "true"
  annotations:
    package-operator.run/phase: integrations
    package-operator.run/collision-protection: IfNoController
data:
  service-orchestration.json: "{}"
  rh-infra-service-orchestration.json: "{}"
