apiVersion: v1
kind: Template
parameters:
  - name: CHANNEL
    required: false
  - name: OPERATOR_IMAGE
    required: true
  - name: PKO_IMAGE
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE_DIGEST
    required: true
  - name: REPO_NAME
    value: pagerduty-operator
    required: true
  - name: FEDRAMP
    value: "false"
  - name: ACKNOWLEDGE_TIMEOUT
    required: true
  - name: RESOLVE_TIMEOUT
    required: true
  - name: ESCALATION_POLICY
    required: true
  - name: ESCALATION_POLICY_SILENT
    required: true
  - name: SERVICE_PREFIX
    required: true
  - name: SILENT_ALERT_LEGALENTITY_IDS
    value: '[]'
  - name: SCALE_TEST_ESCALATION_POLICY
    required: true
  - name: SCALE_TEST_SERVICE_PREFIX
    required: true
  - name: SCALE_TEST_LEGALENTITY_IDS
    value: '[]'
  - name: SERVICE_ORCHESTRATION_ENABLED
    value: "false"
  - name: SERVICE_ORCHESTRATION_RULE_CONFIGMAP
    value: "osd-serviceorchestration"
  - name: ALERT_GROUPING_TYPE
    value: ""
  - name: ALERT_GROUPING_TIMEOUT
    value: "0"
  - name: SERVICE_ORCHESTRATION_RULES
    value: "{}"
  - name: RH_INFRA_SERVICE_ORCHESTRATION_RULES
    value: "{}"
metadata:
  name: clusterpackage-template
objects:
  - apiVersion: package-operator.run/v1alpha1
    kind: ClusterPackage
    metadata:
      name: "${REPO_NAME}"
      annotations:
        package-operator.run/collision-protection: IfNoController
    spec:
      image: ${PKO_IMAGE}:${IMAGE_TAG}
      config:
        image: ${OPERATOR_IMAGE}:${IMAGE_TAG}
        fedramp: ${FEDRAMP}
        acknowledgeTimeout: ${{ACKNOWLEDGE_TIMEOUT}}
        resolveTimeout: ${{RESOLVE_TIMEOUT}}
        escalationPolicy: ${ESCALATION_POLICY}
        escalationPolicySilent: ${ESCALATION_POLICY_SILENT}
        servicePrefix: ${SERVICE_PREFIX}
        silentAlertLegalEntityIds: ${{SILENT_ALERT_LEGALENTITY_IDS}}
        scaleTestEscalationPolicy: ${SCALE_TEST_ESCALATION_POLICY}
        scaleTestServicePrefix: ${SCALE_TEST_SERVICE_PREFIX}
        scaleTestLegalEntityIds: ${{SCALE_TEST_LEGALENTITY_IDS}}
        serviceOrchestrationEnabled: ${SERVICE_ORCHESTRATION_ENABLED}
        serviceOrchestrationRuleConfigmap: ${SERVICE_ORCHESTRATION_RULE_CONFIGMAP}
        alertGroupingType: ${ALERT_GROUPING_TYPE}
        alertGroupingTimeout: ${{ALERT_GROUPING_TIMEOUT}}
        serviceOrchestrationRules: ${SERVICE_ORCHESTRATION_RULES}
        rhInfraServiceOrchestrationRules: ${RH_INFRA_SERVICE_ORCHESTRATION_RULES}
